### ISSUE TITLE
[JS SDK]: TypeError: Found non-callable @@iterator

### ISSUE THREAD

**Issue by jelling** [wandb/wandb-js#13]
## Error
```
Streaming LangChain activity to W&B at: https://wandb.ai/reboot/audio-script/runs/b8ro6g9a
C:\dev\rbt\tv\functions\node_modules\langchain\dist\callbacks\manager.cjs:428
        this.tags.push(...tags);
                          ^

TypeError: Found non-callable @@iterator
    at CallbackManager.addTags (C:\dev\rbt\tv\functions\node_modules\langchain\dist\callbacks\manager.cjs:428:19)
    at CallbackManager.configure (C:\dev\rbt\tv\functions\node_modules\langchain\dist\callbacks\manager.cjs:533:33)
    at WandbTracer.init (C:\dev\rbt\tv\functions\node_modules\@wandb\sdk\dist\sdk\integrations\langchain\index.cjs:31:59)
    at foo (c:\dev\rbt\tv\functions\src\script\infer\characters\foo.ts:17:18)
```

## Code

```typescript
import { OpenAI } from "langchain/llms/openai";
import { LLMChain } from "langchain/chains";
import { PromptTemplate } from "langchain/prompts";
import { WandbTracer } from "@wandb/sdk/integrations/langchain";

export const foo = async () => {
  const llm = new OpenAI({});
  const prompt = PromptTemplate.fromTemplate(
    "What is a good name for a company that makes {product}?"
  );

  const tracer = await WandbTracer.init({ project: "audio-script" });

  const chain = new LLMChain({
    llm,
    prompt,
  });

  const result = await chain.run("colorful socks", tracer);
};

foo();
```

Note: without the wandb `tracer` callback the code works fine. Also, this code is the example code from langchain.js. All libraries installed today fwiw.

P.s. the `wandb-js` repo appears to be using the issue templates from another repo. The original tag said [CLI] and referred to Python.

### Environment

WandB version: `0.5.1`

OS: `windows`

Python version: Node JS :) 

Versions of relevant libraries:    "langchain": "^0.0.143",

**Comment by matthijs166** [comment]
Got the same error with langchain v0.0.144

**Comment by utrerf** [comment]
Got the same issue as well

**Comment by coryvirok** [comment]
Same using langchain@0.0.197-rc.1

**Comment by matthijs166** [comment]
We just stopped using langchain and used the native OpenAI client. Langchain is just a pain in the ass to use....
